# Makefile for the AOPify pass
ROOT=../..

include $(ROOT)/Makefile.inc

PASSNAME := analyze_hotness
OBJS := analyze_hotness.o  $(INCLUDE_UTILS_DIR)/llvm_utils.o

IFLAGS :=


include ../Makefile.inc


